apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tourimse-sitd
  namespace: argocd
spec:
  destination:
    namespace: tourisme-sitd
    server: 'https://kubernetes.default.svc'
  source:
    path: impdeploy/
    repoURL: 'https://github.com/davidagoua/nginx-depl.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true