apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-nginx
spec:
  rules:
    - host: testplate.test
      http:
        paths:
          - backend:
              service:
                name: frontend-svc
                port:
                  number: 80
            pathType: Prefix
            path: /

      