apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-depl
  template:
    metadata:
      name: nginx-depl
      labels:
        app: nginx-depl
    spec:
      containers:
        - name: nginx-depl
          image: nginx:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-depl-svc
spec:
  selector:
    app: nginx-depl
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31082
      