apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: impdeploy
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: caddy/caddy
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    tiers: front
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - port: 80
