apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-backend
  labels:
    app: main-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-backend
  template:
    metadata:
      name: main-backend
      labels:
        app: main-backend
    spec:
      containers:
        - name: main-backend
          image: caddy/caddy
          imagePullPolicy: IfNotPresent
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: main-backend-svc
spec:
  selector:
    app: main-backend
  ports:
    - port: 80
