apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-backend
  labels:
    app: main-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-backend
  template:
    metadata:
      name: main-backend
      labels:
        app: main-backend
    spec:
      containers:
        - name: main-backend
          image: alpine
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      