apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: impdeploy
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  namespace: impdeploy
  name: user-service-svc
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      